/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'admin' at '15-12-30 下午4:11' with Gradle 2.9
 *
 * @author admin, @date 15-12-30 下午4:11
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
